#!/bin/bash

USER=$(whoami)
DATE=$(date)
HOSTNAME=$(hostname)
DISTRO=$(lsb_release -d | cut -f2)
UPTIME=$(uptime -p)

CPU=$(lscpu | grep "Model name" | cut -d: -f2 | sed 's/^ //')
RAM=$(free -h | grep Mem | awk '{print $2}')
DISK=$(lsblk -o NAME,SIZE,MODEL | grep -E "sd|nvme")
VIDEO=$(lspci | grep -i vga | awk -F: '{print $2}' | sed 's/^ //')

FQDN=$(hostname --fqdn)
IP_ADDR=$(ip a | grep 'inet ' | grep -v inet6 | awk '{print $2}' | cut -d/ -f1 | head -n 1)
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')

USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
DISK_SPACE=$(df -h | grep "^/" | awk '{print $1 " " $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average: ' '{ print $2 }')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d: -f2 | sort -u | tr '\n' ',' | sed 's/,$//')
UFW_STATUS=$(ufw status | grep -i "Status" | awk '{print $2}')

echo -e "\nSystem Report generated by $USER, $DATE\n"

echo "System Information"

echo "------------------"

echo "Hostname: $HOSTNAME"

echo "OS: $DISTRO"

echo "Uptime: $UPTIME"

echo

echo "Hardware Information"

echo "--------------------"

echo "cpu: $CPU"

echo "Ram: $RAM"

echo "Disk(s):"

echo "$DISK"

echo "Video: $VIDEO"

echo

echo "Network Information"

echo "-------------------"

echo "FQDN: $FQDN"

echo "Host Address: $IP_ADDR"

echo "Gateway IP: $GATEWAY"

echo "DNS Server: $DNS_SERVER"

echo

echo "System Status"

echo "-------------"

echo "Users Logged In: $USERS_LOGGED_IN"

echo "Disk Space: $DISK_SPACE"

echo "Process Count: $PROCESS_COUNT"

echo "Load Averages: $LOAD_AVERAGES"

echo "Listening Network Ports: $LISTENING_PORTS"

echo "UFW Status: $UFW_STATUS"

echo -e "\n"
